'use strict';
const API='https://api.centuryroom.cn';
const $=id=>document.getElementById(id);
const groups={鼓手:['汤','妹','yo','哲','本','项','诺'],MC:['远','豆','狮','森','Carlos'],小号:['河','宏'],Dancer:['Gus','彭俊维','刘俊龙','小熊','小咖喱','Igor']};
const actors=Object.values(groups).flat(),ghostActors=['彭俊维','哲','本'];
const blankShow=()=>({head:'',tail:'',mc:'',trumpet:'',dancers:['','']});
const blankSchedule=(count=4)=>({format:2,count,shows:Array.from({length:count},blankShow),rest:{},night:{'彭俊维':'','哲':'','本':''}});
const copy=value=>JSON.parse(JSON.stringify(value));
let currentUser=null,registration=false,version=0,loadedDay=null,sequence=0,data=blankSchedule(),working=null,personal=false,editing=false,dirty=false,saving=false;
function node(tag,text,className){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(className)e.className=className;return e;}
function message(text,error=false){$('message').hidden=!text;$('message').textContent=text;$('message').classList.toggle('error',error);}
async function api(path,method='GET',body){let r;try{r=await fetch(API+path,{method,credentials:'include',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});}catch{throw Error('连接失败，请重试');}const result=await r.json();if(!r.ok){if(r.status===401&&!['/auth/login','/auth/register'].includes(path)){currentUser=null;renderAccount();}throw Error(result.message||'操作失败');}return result;}
function actorOptions(select){for(const [group,names] of Object.entries(groups)){const optgroup=node('optgroup');optgroup.label=group;for(const name of names){const option=node('option',name);option.value=name;optgroup.append(option);}select.append(optgroup);}}
actorOptions($('actor'));actorOptions($('record-actor'));
function choice(values,value,label){const s=node('select');s.setAttribute('aria-label',label);for(const v of values){const option=node('option',v);option.value=v;s.append(option);}if(value==='其他'&&!values.includes(value)){const old=node('option','其他（旧记录）');old.value=value;old.disabled=true;s.append(old);}s.value=value||'';return s;}
function table(headers,rows,className){const wrap=node('div',undefined,'table-wrap'),t=node('table',undefined,className),head=node('thead'),h=node('tr');headers.forEach(v=>h.append(node('th',v)));head.append(h);t.append(head);const body=node('tbody');rows.forEach(values=>{const r=node('tr');values.forEach(v=>{const cell=node('td');cell.append(v instanceof Node?v:document.createTextNode(v==null?'':String(v)));r.append(cell);});body.append(r);});t.append(body);wrap.append(t);return wrap;}
function roles(show,actor){return [show.head===actor?'车头':'',show.tail===actor?'车尾':'',show.mc===actor?'MC':'',show.trumpet===actor?'小号':'',show.dancers.includes(actor)?'Dancer':''].filter(Boolean);}
function dateString(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
$('day').value=dateString(new Date());
function authMode(register){registration=register;$('login-tab').classList.toggle('selected',!register);$('register-tab').classList.toggle('selected',register);for(const id of ['name-label','confirm-label','username-hint','registration-note'])$(id).hidden=!register;$('name').required=register;$('confirm-password').required=register;$('password').autocomplete=register?'new-password':'current-password';$('auth-submit').textContent=register?'注册':'登录';message('');}
$('login-tab').onclick=()=>authMode(false);$('register-tab').onclick=()=>authMode(true);
$('auth-form').onsubmit=async e=>{e.preventDefault();const username=$('username').value.trim(),password=$('password').value;if(registration&&password!==$('confirm-password').value)return message('两次密码不一致',true);$('auth-submit').disabled=true;try{if(registration){await api('/auth/register','POST',{username,password,name:$('name').value.trim()});authMode(false);$('password').value='';$('confirm-password').value='';message('注册成功，请登录');}else{currentUser=(await api('/auth/login','POST',{username,password})).user;$('password').value='';await renderAccount();}}catch(e){message(e.message,true);}finally{$('auth-submit').disabled=false;}};
async function renderAccount(){const u=currentUser,approved=u?.status==='approved',admin=approved&&u.role==='admin';$('auth').hidden=!!u;$('account').hidden=!u;$('pending').hidden=!u||approved;$('app').hidden=!approved;$('edit').hidden=!admin;$('accounts').hidden=!admin;if(u)$('welcome').textContent=u.name;if(!approved){sequence++;editing=false;dirty=false;working=null;$('schedule-view').replaceChildren();$('users').replaceChildren();return;}setEditing(false);await loadSchedule();}
$('refresh-account').onclick=async()=>{try{currentUser=(await api('/auth/me')).user;await renderAccount();}catch(e){message(e.message,true);}};
$('logout').onclick=async()=>{if(saving)return;if(dirty&&!confirm('放弃未保存的修改？'))return;try{await api('/auth/logout','POST',{});currentUser=null;dirty=false;await renderAccount();message('');}catch(e){message(e.message,true);}};
function tag(text){if(!text)return '';return node('span',text,'role-tag'+(text==='休息'?' rest':text==='鬼'?' ghost':''));}
function renderView(){const day=$('day').value;const d=new Date(day+'T12:00:00');$('day-title').textContent=day.slice(5).replace('-','月')+'日 · '+d.toLocaleDateString('zh-CN',{weekday:'short'});$('show-total').textContent=data.count+' 场';$('actor').hidden=!personal;$('all-view').classList.toggle('selected',!personal);$('personal-view').classList.toggle('selected',personal);const view=$('schedule-view');view.replaceChildren();if(personal){const actor=$('actor').value;const rows=data.shows.map((show,i)=>{const duties=roles(show,actor).join(' / ');return [`第 ${i+1} 场`,tag(duties||(data.rest[actor]?.[i]?'休息':''))];});if(ghostActors.includes(actor))rows.push(['晚场',tag(data.night[actor]||'')]);view.append(table(['场次',actor],rows,'personal-table'));}else{view.append(table(['场次','车头','车尾','MC','小号','Dancer 1','Dancer 2'],data.shows.map((s,i)=>[i+1,s.head,s.tail,s.mc,s.trumpet,...s.dancers]),'roster-table'));}}
$('all-view').onclick=()=>{personal=false;renderView();};$('personal-view').onclick=()=>{personal=true;renderView();};$('actor').onchange=renderView;
async function loadSchedule(){const tick=++sequence,day=$('day').value;loadedDay=null;$('edit').disabled=true;try{const r=await api('/schedules/'+day);if(tick!==sequence||currentUser?.status!=='approved')return;data=r.schedule?.data||blankSchedule();version=r.schedule?.version||0;loadedDay=day;renderView();message('');}catch(e){if(tick===sequence){$('schedule-view').replaceChildren();message(e.message,true);}}finally{if(tick===sequence)$('edit').disabled=!loadedDay;}}
$('day').onchange=loadSchedule;for(const [id,delta] of [['prev-day',-1],['next-day',1]])$(id).onclick=()=>{const d=new Date($('day').value+'T12:00:00');d.setDate(d.getDate()+delta);$('day').value=dateString(d);loadSchedule();};$('today').onclick=()=>{$('day').value=dateString(new Date());loadSchedule();};
function setEditing(value){editing=value;$('editor').hidden=!value;$('display').hidden=value;$('edit').hidden=value||currentUser?.role!=='admin';for(const id of ['prev-day','next-day','day','today'])$(id).disabled=value;$('all-view').disabled=value;$('personal-view').disabled=value;$('actor').disabled=value;}
function clearConflictingRest(){for(const actor of actors){if(working.rest[actor])working.shows.forEach((show,i)=>{if(roles(show,actor).length)working.rest[actor][i]=false;});}}
function fillShows(){const headers=['场次','车头','车尾','MC','小号','Dancer 1','Dancer 2',''];const rows=working.shows.map((show,i)=>{const cells=[i+1];for(const [key,list] of [['head',groups.鼓手],['tail',groups.鼓手],['mc',groups.MC],['trumpet',groups.小号],['dancer0',groups.Dancer],['dancer1',groups.Dancer]]){const isDancer=key.startsWith('dancer'),at=+key.slice(-1);const value=isDancer?show.dancers[at]:show[key];const labels={head:'车头',tail:'车尾',mc:'MC',trumpet:'小号',dancer0:'Dancer 1',dancer1:'Dancer 2'};const select=choice(['',...list],value,`第 ${i+1} 场 ${labels[key]}`);select.onchange=()=>{if(isDancer)show.dancers[at]=select.value;else show[key]=select.value;dirty=true;clearConflictingRest();renderRest();};cells.push(select);}const b=node('button','沿用上一场');b.type='button';b.disabled=i===0;b.onclick=()=>{working.shows[i]=copy(working.shows[i-1]);dirty=true;clearConflictingRest();fillShows();renderRest();};cells.push(b);return cells;});$('show-fields').replaceChildren(table(headers,rows,'edit-table'));}
function renderRest(){const actor=$('record-actor').value;$('rest-fields').replaceChildren();working.shows.forEach((show,i)=>{const row=node('div',undefined,'record-row'),duties=roles(show,actor).join(' / ');row.append(node('span',`第 ${i+1} 场`));if(duties)row.append(tag(duties));else{const select=choice(['','休息'],working.rest[actor]?.[i]?'休息':'',`第 ${i+1} 场 ${actor} 个人记录`);select.onchange=()=>{(working.rest[actor]??=Array(working.count).fill(false))[i]=select.value==='休息';dirty=true;};row.append(select);}$('rest-fields').append(row);});}
$('record-actor').onchange=()=>{if(working)renderRest();};
function fillForm(){ $('show-count').value=working.count;fillShows();$('record-actor').value=$('actor').value;renderRest();$('night-fields').replaceChildren();ghostActors.forEach(actor=>{const label=node('label',actor),s=choice(['','鬼','休息'],working.night[actor]||'',`${actor} 晚场`);s.onchange=()=>{working.night[actor]=s.value;dirty=true;};label.append(s);$('night-fields').append(label);});}
$('edit').onclick=()=>{if(!loadedDay)return;working=copy(data);dirty=false;fillForm();setEditing(true);message('');};
$('show-count').onchange=()=>{const count=+$('show-count').value;if(count<working.count&&working.shows.slice(count).some(s=>Object.values(s).flat().some(Boolean))&&!confirm('减少场数会移除后面的安排，继续？')){$('show-count').value=working.count;return;}working.count=count;working.shows=Array.from({length:count},(_,i)=>working.shows[i]||blankShow());for(const actor of Object.keys(working.rest))working.rest[actor]=Array.from({length:count},(_,i)=>working.rest[actor][i]||false);dirty=true;fillShows();renderRest();};
$('cancel-edit').onclick=()=>{if(saving)return;if(dirty&&!confirm('放弃未保存的修改？'))return;dirty=false;working=null;setEditing(false);renderView();message('');};
$('schedule-form').onsubmit=async e=>{e.preventDefault();if(saving||loadedDay!==$('day').value)return;saving=true;for(const input of $('schedule-form').querySelectorAll('input,select,button,summary'))input.disabled=true;$('logout').disabled=true;try{const r=await api('/schedules/'+loadedDay,'PUT',{data:working,version});version=r.version;data=copy(working);dirty=false;working=null;setEditing(false);renderView();message('已保存');}catch(e){message(e.message,true);}finally{saving=false;for(const input of $('schedule-form').querySelectorAll('input,select,button,summary'))input.disabled=false;$('logout').disabled=false;const first=$('show-fields').querySelector('tbody tr:first-child button');if(first)first.disabled=true;}};
async function loadUsers(){try{const r=await api('/admin/users');$('users').replaceChildren(table(['姓名','用户名','权限','状态',''],r.users.map(u=>{const actions=node('div',undefined,'user-actions');function action(label,change,prompt){const b=node('button',label);b.type='button';b.onclick=async()=>{if(prompt&&!confirm(prompt))return;b.disabled=true;try{await api('/admin/users/'+u.id,'PUT',change);await loadUsers();message('已更新，请对方重新登录');}catch(e){b.disabled=false;message(e.message,true);}};actions.append(b);}if(u.id!==r.ownerId){if(u.role!=='admin'){for(const [status,label] of [['approved','批准查看'],['disabled','停用']])if(u.status!==status)action(label,{status});if(r.canManageRoles)action('设为管理员',{role:'admin',status:'approved'},`将 ${u.name}（${u.username}）设为管理员？她将可以编辑排班和审批账号。`);}else if(r.canManageRoles)action('改为查看',{role:'viewer'},`将 ${u.name}（${u.username}）改为仅查看？`);}return [u.name,u.username,u.role==='admin'?'管理员':'仅查看',{pending:'待批准',approved:'已批准',disabled:'已停用'}[u.status],actions];})));}catch(e){message(e.message,true);}}
$('accounts').ontoggle=()=>{if($('accounts').open)loadUsers();};$('refresh-users').onclick=loadUsers;
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
(async()=>{try{currentUser=(await api('/auth/me')).user;await renderAccount();}catch(e){currentUser=null;await renderAccount();}})();
