'use strict';
const API='https://api.centuryroom.cn';
const $=id=>document.getElementById(id);
const drummers=['汤世纪','yoyo','妹宝','小哲','Ben','阿诺','大象'];
const roster=Object.entries({MC:['欧修远','Curtis','Jason'],舞者:['Gus','彭俊维'],小号:['小河','小宏']}).flatMap(([group,names])=>names.map(name=>({group,name,shift:'待定'})));
let currentUser=null, registration=false, version=0, loadedDay=null, loadSequence=0;
function message(text,error=false){$('message').hidden=!text;$('message').textContent=text;$('message').classList.toggle('error',error);}
async function api(path,method='GET',data){let response;try{response=await fetch(API+path,{method,credentials:'include',headers:data?{'Content-Type':'application/json'}:{},body:data?JSON.stringify(data):undefined});}catch{throw Error('无法连接服务，请检查网络后重试');}const result=await response.json();if(!response.ok){if(response.status===401 && path!=='/auth/login' && path!=='/auth/register'){currentUser=null;renderAccount();}throw Error(result.message||'操作失败');}return result;}
function element(tag,text,className){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(className)e.className=className;return e;}
function table(headers,rows){const wrap=element('div',undefined,'table-wrap'),t=element('table'),thead=element('thead'),tr=element('tr');headers.forEach(h=>tr.append(element('th',h)));thead.append(tr);t.append(thead);const body=element('tbody');rows.forEach(row=>{const r=element('tr');row.forEach(value=>{const cell=element('td');cell.append(value instanceof Node?value:document.createTextNode(String(value)));r.append(cell);});body.append(r);});t.append(body);wrap.append(t);return wrap;}
function select(options,value,labelText){const label=element('label',labelText),s=element('select');options.forEach(v=>{const o=element('option',v||'无特殊安排');o.value=v;s.append(o);});s.value=value;label.append(s);return label;}
function dateString(date){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;}
$('day').value=dateString(new Date());
function authMode(register){registration=register;$('login-tab').classList.toggle('selected',!register);$('register-tab').classList.toggle('selected',register);for(const id of ['name-label','confirm-label','password-hint','registration-note'])$(id).hidden=!register;$('name').required=register;$('confirm-password').required=register;$('password').minLength=register?15:1;$('password').autocomplete=register?'new-password':'current-password';$('auth-submit').textContent=register?'注册账号':'登录';message('');}
$('login-tab').onclick=()=>authMode(false);$('register-tab').onclick=()=>authMode(true);
$('auth-form').onsubmit=async e=>{e.preventDefault();const username=$('username').value.trim(),password=$('password').value;if(registration && password!==$('confirm-password').value)return message('两次输入的密码不一致',true);$('auth-submit').disabled=true;try{if(registration){await api('/auth/register','POST',{username,password,name:$('name').value.trim()});authMode(false);$('password').value='';$('confirm-password').value='';message('注册成功，请登录并等待管理员批准');}else{const r=await api('/auth/login','POST',{username,password});$('password').value='';currentUser=r.user;message('');await renderAccount();}}catch(err){message(err.message,true);}finally{$('auth-submit').disabled=false;}};
async function renderAccount(){const u=currentUser;$('auth').hidden=!!u;$('account').hidden=!u;$('schedule-section').hidden=!u||u.status!=='approved';$('admin').hidden=!u||u.role!=='admin'||u.status!=='approved';$('refresh-account').hidden=!u||u.status==='approved';if(!u){$('schedule-view').replaceChildren();$('users').replaceChildren();return;}$('welcome').textContent=`${u.name}，你好`;$('account-state').textContent=u.status==='approved'?(u.role==='admin'?'管理员 · 可维护排班和批准账号':'已批准 · 可查看已发布排班'):'等待管理员批准，批准后重新登录即可查看排班';if(u.status==='approved'){await loadSchedule();if(u.role==='admin')await loadUsers();}}
async function refreshAccount(){try{currentUser=(await api('/auth/me')).user;await renderAccount();}catch(e){message(e.message,true);}}
$('refresh-account').onclick=refreshAccount;
$('logout').onclick=async()=>{try{await api('/auth/logout','POST');currentUser=null;renderAccount();message('已退出登录');}catch(e){message(e.message,true);}};
function blankSchedule(){return {count:4,shows:Array.from({length:4},()=>({period:'上午',drummers:['','']})),roster:roster.map(x=>({...x})),special:{},note:'',published:false};}
function fillShows(shows){$('show-fields').replaceChildren();shows.forEach((show,i)=>{const row=element('div',undefined,'show-row');row.append(element('span',`第 ${i+1} 场`),select(['上午','下午'],show.period,'时段'),select(['',...drummers],show.drummers[0],'鼓手一'),select(['',...drummers],show.drummers[1],'鼓手二'));$('show-fields').append(row);});}
function readShows(){return [...$('show-fields').children].map(row=>{const s=row.querySelectorAll('select');return {period:s[0].value,drummers:[s[1].value,s[2].value]};});}
function fillForm(data){$('show-count').value=data.count;$('published').value=String(data.published);fillShows(data.shows);$('roster-fields').replaceChildren();roster.forEach(r=>{const label=element('label',`${r.group} · ${r.name}`),input=element('input');input.value=data.roster.find(x=>x.group===r.group&&x.name===r.name)?.shift||'待定';input.maxLength=40;input.required=true;label.append(input);$('roster-fields').append(label);});$('special-fields').replaceChildren();drummers.forEach(name=>$('special-fields').append(select(['','休息',...(['小哲','Ben'].includes(name)?['鬼屋']:[])],data.special[name]||'',name)));$('schedule-note').value=data.note;}
$('show-count').onchange=()=>{const count=+$('show-count').value,existing=readShows();fillShows(Array.from({length:count},(_,i)=>existing[i]||{period:i<3?'上午':'下午',drummers:['','']}));};
function renderSchedule(schedule){const view=$('schedule-view');view.replaceChildren();if(!schedule){view.append(element('p','当天尚无已发布排班。', 'empty'));return;}const data=schedule.data;view.append(element('span',schedule.published?'已发布':'草稿 · 仅管理员可见','badge'),element('h3',`${schedule.day} · ${data.count} 场`));view.append(table(['场次','时段','鼓手搭档'],data.shows.map((s,i)=>[`第 ${i+1} 场`,s.period,s.drummers.join(' / ')])));view.append(element('h3','岗位安排'),table(['岗位','姓名','安排'],data.roster.map(r=>[r.group,r.name,r.shift])));const drumRows=drummers.map(name=>{const played=data.shows.filter(s=>s.drummers.includes(name)),am=played.filter(s=>s.period==='上午').length,pm=played.length-am;let shift=played.length===data.count?'全天':played.length?[am?`上午 ${am} 场`:'',pm?`下午 ${pm} 场`:''].filter(Boolean).join(' · '):'未安排演出';if(data.special[name])shift=played.length?`${shift} · ${data.special[name]}`:data.special[name];return ['鼓手',name,shift];});view.append(element('h3','鼓手出席'),table(['岗位','姓名','安排'],drumRows));if(data.note)view.append(element('h3','备注'),element('p',data.note,'note'));view.append(element('small','更新于 '+new Date(schedule.updatedAt).toLocaleString('zh-CN')));}
async function loadSchedule(){const sequence=++loadSequence,day=$('day').value;loadedDay=null;$('save-schedule').disabled=true;try{const r=await api('/schedules/'+day);if(sequence!==loadSequence)return;version=r.schedule?.version||0;loadedDay=day;renderSchedule(r.schedule);if(currentUser?.role==='admin')fillForm(r.schedule?.data||blankSchedule());message('');}catch(e){if(sequence!==loadSequence)return;$('schedule-view').replaceChildren(element('p','排班加载失败，请重试','empty'));message(e.message,true);}finally{if(sequence===loadSequence)$('save-schedule').disabled=!loadedDay;}}
$('day').onchange=loadSchedule;$('refresh-schedule').onclick=loadSchedule;
for(const [id,delta] of [['prev-day',-1],['next-day',1]])$(id).onclick=()=>{const d=new Date($('day').value+'T12:00:00');d.setDate(d.getDate()+delta);$('day').value=dateString(d);loadSchedule();};
$('schedule-form').onsubmit=async e=>{e.preventDefault();if(loadedDay!==$('day').value)return message('请先加载所选日期',true);$('save-schedule').disabled=true;const day=loadedDay,data={count:+$('show-count').value,shows:readShows(),roster:roster.map((r,i)=>({...r,shift:$('roster-fields').children[i].querySelector('input').value.trim()})),special:Object.fromEntries(drummers.map((name,i)=>[name,$('special-fields').children[i].querySelector('select').value])),note:$('schedule-note').value,published:$('published').value==='true'};try{await api('/schedules/'+day,'PUT',{data,version});if($('day').value===day)await loadSchedule();message(data.published?'当天排班已发布':'当天排班已保存为草稿');}catch(err){message(err.message,true);}finally{$('save-schedule').disabled=!loadedDay;}};
async function loadUsers(){try{const r=await api('/admin/users');$('users').replaceChildren(table(['姓名','用户名','状态','操作'],r.users.map(u=>{const actions=element('div',undefined,'user-actions');if(u.role!=='admin'){for(const [status,label] of [['approved','批准'],['disabled','停用']]){if(u.status===status)continue;const b=element('button',label);b.type='button';b.onclick=async()=>{b.disabled=true;try{await api('/admin/users/'+u.id,'PUT',{status});await loadUsers();message(label+'成功，对方需重新登录');}catch(e){message(e.message,true);b.disabled=false;}};actions.append(b);}}else actions.textContent='管理员';return [u.name,u.username,{pending:'待批准',approved:'已批准',disabled:'已停用'}[u.status],actions];})));}catch(e){message(e.message,true);}}
$('refresh-users').onclick=loadUsers;
(async()=>{try{currentUser=(await api('/auth/me')).user;await renderAccount();}catch(e){if(currentUser)message(e.message,true);else renderAccount();}})();
