import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
import worker from './worker.mjs';
import {blankSchedule,validateSchedule,normalizeSchedule} from './model.mjs';
const db=new DatabaseSync(':memory:');db.exec(readFileSync(new URL('./schema.sql',import.meta.url),'utf8'));
class Statement {constructor(sql,args=[]){this.sql=sql;this.args=args;}bind(...args){return new Statement(this.sql,args);}async first(){return db.prepare(this.sql).get(...this.args)||null;}async all(){return {results:db.prepare(this.sql).all(...this.args)};}async run(){const r=db.prepare(this.sql).run(...this.args);return {meta:{changes:Number(r.changes)}};}}
const env={DB:{prepare:sql=>new Statement(sql),async batch(items){db.exec('BEGIN');try{const r=[];for(const s of items)r.push(await s.run());db.exec('COMMIT');return r;}catch(e){db.exec('ROLLBACK');throw e;}}}};
let calls=0;
async function request(path,method='GET',data,cookie='',origin='https://www.centuryroom.cn') {calls++;const r=await worker.fetch(new Request('https://api.centuryroom.cn'+path,{method,headers:{Origin:origin,'Content-Type':'application/json','CF-Connecting-IP':'127.0.0.1',Cookie:cookie},body:data?JSON.stringify(data):undefined}),env);return {status:r.status,body:await r.json(),cookie:r.headers.get('Set-Cookie')?.split(';')[0],headers:r.headers};}
const account={username:'test_viewer',name:'测试查看人',password:'local-test-only-password-2026'};
assert.equal((await request('/schedules/2026-10-06')).status,401);
assert.equal((await request('/auth/register','POST',{...account,role:'admin',status:'approved'})).status,201);
assert.equal(db.prepare('SELECT role FROM users WHERE username=?').get(account.username).role,'viewer');
let login=await request('/auth/login','POST',account);assert.equal(login.status,200);assert.match(login.headers.get('Set-Cookie'),/HttpOnly; Secure; SameSite=Lax/);let cookie=login.cookie;
assert.equal((await request('/schedules/2026-10-06','GET',null,cookie)).status,403);
assert.equal((await request('/admin/users','GET',null,cookie)).status,403);
assert.equal((await request('/auth/login','POST',{...account,password:'wrong'})).status,401);
await request('/auth/register','POST',{username:'test_admin',name:'测试管理员',password:account.password});
db.exec("UPDATE users SET status='approved',role='admin' WHERE username='test_admin'");
const admin=(await request('/auth/login','POST',{username:'test_admin',password:account.password})).cookie;
const viewer=db.prepare('SELECT id FROM users WHERE username=?').get(account.username).id;
env.OWNER_ID=db.prepare("SELECT id FROM users WHERE username='test_admin'").get().id;
assert.equal((await request('/admin/users','GET',null,admin)).body.canManageRoles,true);
assert.equal((await request('/admin/users/'+viewer,'PUT',{status:'approved'},admin)).status,200);
assert.equal((await request('/auth/me','GET',null,cookie)).status,401);
cookie=(await request('/auth/login','POST',account)).cookie;
assert.equal((await request('/admin/users','GET',null,cookie)).status,403);
const data=blankSchedule();
data.shows[0]={head:'汤',tail:'妹',mc:'远',trumpet:'河',dancers:['Gus','其他']};
data.night={'彭俊维':'鬼','哲':'鬼'};
data.rest={yo:[true,false,false,false]};
assert.equal((await request('/schedules/2026-10-06','PUT',{version:0,data},cookie)).status,403);
assert.equal((await request('/schedules/2026-10-06','PUT',{version:0,data},admin,'https://evil.example')).status,403);
assert.equal((await request('/schedules/2026-02-30','PUT',{version:0,data},admin)).status,400);
assert.equal((await request('/schedules/2026-10-06','PUT',{version:0,data:{...data,shows:data.shows.map(s=>({...s,head:'yo',tail:'yo'}))}},admin)).status,400);
assert.equal((await request('/schedules/2026-10-06','PUT',{version:0,data:{...data,shows:data.shows.map(s=>({...s,dancers:['其他','其他']}))}},admin)).status,400);
assert.equal((await request('/schedules/2026-10-06','PUT',{version:0,data:{...data,rest:{汤:[true,false,false,false]}}},admin)).status,400);
assert.equal((await request('/schedules/2026-10-06','PUT',{version:0,data:{...data,night:{本:'鬼'}}},admin)).status,400);
assert.equal((await request('/schedules/2026-10-06','PUT',{version:0,data},admin)).status,200);
let saved=(await request('/schedules/2026-10-06','GET',null,cookie)).body.schedule;
assert.equal(saved.data.format,2);assert.equal(saved.data.shows[1].head,'');assert.equal(saved.data.night.哲,'鬼');
assert.equal((await request('/schedules/2026-10-06','PUT',{version:0,data},admin)).status,409);
assert.equal((await request('/schedules/2026-10-06','PUT',{version:1,data:blankSchedule(6)},admin)).status,200);
assert.equal((await request('/schedules/2026-10-06','GET',null,cookie)).body.schedule.version,2);
assert.equal((await request('/schedules/2026-10-06','GET',null,cookie)).body.schedule.data.shows.length,6);
assert.equal(db.prepare('SELECT COUNT(*) AS n FROM schedule_archive').get().n,1);
assert.equal((await request('/schedules/2026-10-06','PUT',{version:1,data},admin)).status,409);
for(const count of [4,5,6])assert.equal(validateSchedule(blankSchedule(count)).count,count);
const legacy={count:4,shows:Array.from({length:4},()=>({drummers:['汤世纪','妹宝']})),roster:[{name:'小宏',shift:'全天'},{name:'Gus',shift:'全天'},{name:'彭俊维',shift:'鬼屋'},{name:'Curtis',shift:'全天'}],special:{小哲:'鬼屋',Ben:'鬼屋',yoyo:'休息'}};
const migrated=normalizeSchedule(legacy);assert.equal(migrated.shows[0].head,'汤');assert.deepEqual(migrated.shows[0].dancers,['Gus','']);assert.equal(migrated.shows[0].mc,'');assert.equal(migrated.night.哲,'鬼');assert.equal(migrated.night.彭俊维,'鬼');assert.equal(migrated.night.本,undefined);assert.equal(migrated.rest.yo[0],true);
db.prepare('INSERT INTO schedules VALUES(?,?,?,?,?,?)').run('2026-10-05',JSON.stringify(legacy),0,1,Date.now(),'legacy');
assert.equal((await request('/schedules/2026-10-05','GET',null,cookie)).body.schedule.data.format,2);
await request('/auth/logout','POST',{},cookie);assert.equal((await request('/auth/me','GET',null,cookie)).status,401);
assert.equal((await request('/admin/users/'+viewer,'PUT',{role:'admin',status:'approved'},admin)).status,200);
cookie=(await request('/auth/login','POST',account)).cookie;
assert.equal((await request('/auth/me','GET',null,cookie)).body.user.role,'admin');
assert.equal((await request('/schedules/2026-10-07','PUT',{version:0,data},cookie)).status,200);
assert.equal((await request('/admin/users/'+env.OWNER_ID,'PUT',{role:'viewer'},cookie)).status,400);
assert.equal((await request('/admin/users/'+viewer,'PUT',{role:'viewer'},cookie)).status,403);
assert.equal((await request('/admin/users/'+viewer,'PUT',{role:'viewer'},admin)).status,200);
assert.equal((await request('/auth/me','GET',null,cookie)).status,401);
const chinese={username:'中文账号',name:'中文姓名',password:'一'};
assert.equal((await request('/auth/register','POST',chinese)).status,201);
assert.equal((await request('/auth/login','POST',chinese)).status,200);
assert.equal((await request('/auth/register','POST',{username:'长密码',name:'测试',password:'长'.repeat(256)})).status,201);
assert.equal((await request('/auth/login','POST',{username:'长密码',password:'长'.repeat(256)})).status,200);
for(let i=0;i<10;i++)await request('/auth/login','POST',{username:'nonexistent',password:'wrong'});
assert.equal((await request('/auth/login','POST',{username:'nonexistent',password:'wrong'})).status,429);
assert.ok(db.prepare('SELECT COUNT(*) AS n FROM audit').get().n>=3);
console.log(`Passed: authentication, pending approval, admin permissions, CSRF, validation, partial saves, dancers, personal rest, independent night duties, legacy conversion, archived revisions, conflicting edits, logout, rate limits (${calls} requests).`);
