import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
import worker from './worker.mjs';
const db=new DatabaseSync(':memory:');db.exec(readFileSync(new URL('./schema.sql',import.meta.url),'utf8'));
class Statement {constructor(sql,args=[]){this.sql=sql;this.args=args;}bind(...args){return new Statement(this.sql,args);}async first(){return db.prepare(this.sql).get(...this.args)||null;}async all(){return {results:db.prepare(this.sql).all(...this.args)};}async run(){const r=db.prepare(this.sql).run(...this.args);return {meta:{changes:Number(r.changes)}};}}
const env={DB:{prepare:sql=>new Statement(sql),async batch(items){db.exec('BEGIN');try{const r=[];for(const s of items)r.push(await s.run());db.exec('COMMIT');return r;}catch(e){db.exec('ROLLBACK');throw e;}}}};
let calls=0;
async function request(path,method='GET',data,cookie='',origin='https://www.centuryroom.cn') {calls++;const r=await worker.fetch(new Request('https://api.centuryroom.cn'+path,{method,headers:{Origin:origin,'Content-Type':'application/json','CF-Connecting-IP':'127.0.0.1',Cookie:cookie},body:data?JSON.stringify(data):undefined}),env);return {status:r.status,body:await r.json(),cookie:r.headers.get('Set-Cookie')?.split(';')[0],headers:r.headers};}
const account={username:'test_viewer',name:'测试查看人',password:'local-test-only-password-2026'};
assert.equal((await request('/schedules/2026-10-06')).status,401);
assert.equal((await request('/auth/register','POST',{...account,role:'admin',status:'approved'})).status,201);
assert.equal(db.prepare('SELECT role FROM users WHERE username=?').get(account.username).role,'viewer');
let login=await request('/auth/login','POST',account);assert.equal(login.status,200);assert.match(login.headers.get('Set-Cookie'),/HttpOnly; Secure; SameSite=Lax/);let cookie=login.cookie;
assert.equal((await request('/schedules/2026-10-06','GET',null,cookie)).status,403);
assert.equal((await request('/admin/users','GET',null,cookie)).status,403);
assert.equal((await request('/auth/login','POST',{...account,password:'wrong'})).status,401);
await request('/auth/register','POST',{username:'test_admin',name:'测试管理员',password:account.password});
db.exec("UPDATE users SET status='approved',role='admin' WHERE username='test_admin'");
const admin=(await request('/auth/login','POST',{username:'test_admin',password:account.password})).cookie;
const viewer=db.prepare('SELECT id FROM users WHERE username=?').get(account.username).id;
assert.equal((await request('/admin/users/'+viewer,'PUT',{status:'approved'},admin)).status,200);
assert.equal((await request('/auth/me','GET',null,cookie)).status,401);
cookie=(await request('/auth/login','POST',account)).cookie;
assert.equal((await request('/admin/users','GET',null,cookie)).status,403);
const data={count:4,shows:Array.from({length:4},(_,i)=>({period:i<2?'上午':'下午',drummers:['汤世纪','yoyo']})),roster:Object.entries({MC:['欧修远','Curtis','Jason'],舞者:['Gus','彭俊维'],小号:['小河','小宏']}).flatMap(([group,names])=>names.map(name=>({group,name,shift:'全天'}))),special:{小哲:'鬼屋'},note:'测试排班',published:false};
assert.equal((await request('/schedules/2026-10-06','PUT',{version:0,data},cookie)).status,403);
assert.equal((await request('/schedules/2026-10-06','PUT',{version:0,data},admin,'https://evil.example')).status,403);
assert.equal((await request('/schedules/2026-02-30','PUT',{version:0,data},admin)).status,400);
assert.equal((await request('/schedules/2026-10-06','PUT',{version:0,data:{...data,shows:data.shows.map(s=>({...s,drummers:['yoyo','yoyo']}))}},admin)).status,400);
assert.equal((await request('/schedules/2026-10-06','PUT',{version:0,data:{...data,special:{yoyo:'休息'}}},admin)).status,400);
assert.equal((await request('/schedules/2026-10-06','PUT',{version:0,data},admin)).status,200);
assert.equal((await request('/schedules/2026-10-06','GET',null,cookie)).body.schedule,null);
assert.equal((await request('/schedules/2026-10-06','PUT',{version:0,data},admin)).status,409);
assert.equal((await request('/schedules/2026-10-06','PUT',{version:1,data:{...data,published:true}},admin)).status,200);
assert.equal((await request('/schedules/2026-10-06','PUT',{version:2,data:{...data,published:true,shows:data.shows.map(s=>({...s,period:'待确认'}))}},admin)).status,400);
assert.equal((await request('/schedules/2026-10-06','GET',null,cookie)).body.schedule.version,2);
assert.equal((await request('/schedules/2026-10-06','PUT',{version:1,data},admin)).status,409);
await request('/auth/logout','POST',{},cookie);assert.equal((await request('/auth/me','GET',null,cookie)).status,401);
for(let i=0;i<10;i++)await request('/auth/login','POST',{username:'nonexistent',password:'wrong'});
assert.equal((await request('/auth/login','POST',{username:'nonexistent',password:'wrong'})).status,429);
assert.ok(db.prepare('SELECT COUNT(*) AS n FROM audit').get().n>=3);
console.log(`Passed: authentication, pending approval, admin permissions, CSRF, validation, draft privacy, conflicting edits, logout, rate limits (${calls} requests).`);
